const products=[{id:1,name:'Гума за електрически скутер',price:18,icon:'🛞'},{id:2,name:'Накладки за спирачки',price:12,icon:'🛑'},{id:3,name:'Контролер',price:25,icon:'⚡'},{id:4,name:'LED фар',price:14,icon:'💡'},{id:5,name:'Дисплей',price:20,icon:'📟'},{id:6,name:'Зарядно устройство',price:28,icon:'🔌'},{id:7,name:'Камера за гума',price:8,icon:'⭕'},{id:8,name:'Комплект ръкохватки',price:10,icon:'🛴'}];
const EMAILJS_PUBLIC_KEY='B-Bg2F2YTMpg_zU5N6PHQ';
const EMAILJS_SERVICE_ID='service_dpk1min';
const EMAILJS_TEMPLATE_ID='template_35llnpl';
let cart=JSON.parse(localStorage.getItem('escooterCart')||'[]');
function renderProducts(){document.getElementById('products').innerHTML=products.map(p=>`<article class="product"><div class="pic">${p.icon}</div><h3>${p.name}</h3><div class="price">€${p.price.toFixed(2)}</div><button class="btn" onclick="add(${p.id})">Добави в количката</button></article>`).join('')}
function add(id){let p=products.find(x=>x.id===id),x=cart.find(x=>x.id===id);x?x.qty++:cart.push({...p,qty:1});save();render()}
function removeItem(id){cart=cart.filter(x=>x.id!==id);save();render()}
function save(){localStorage.setItem('escooterCart',JSON.stringify(cart))}
function row(x){return `<div class="cartRow"><span>${x.name} ×${x.qty}</span><span>€${(x.price*x.qty).toFixed(2)} <button class="qtyBtn" onclick="changeQty(${x.id},-1)">−</button><b>${x.qty}</b><button class="qtyBtn" onclick="changeQty(${x.id},1)">+</button><button class="deleteBtn" onclick="removeItem(${x.id})">🗑️</button></span></div>`}
function changeQty(id,delta){let x=cart.find(x=>x.id===id);if(!x)return;x.qty+=delta;if(x.qty<=0)removeItem(id);else{save();render()}}
function cartProductsTotal(){return cart.reduce((a,x)=>a+x.price*x.qty,0)}
function render(){let n=cart.reduce((a,x)=>a+x.qty,0),t=cartProductsTotal();document.getElementById('count').textContent=n;document.getElementById('miniCount').textContent=n;document.getElementById('total').textContent=`€${t.toFixed(2)}`;let h=cart.length?cart.map(row).join(''):'<p>Няма добавени продукти.</p>';document.getElementById('cartItems').innerHTML=h;document.getElementById('modalItems').innerHTML=h;renderCheckoutTotal()}
function renderCheckoutTotal(){let t=cartProductsTotal(),d=parseFloat(document.getElementById('delivery')?.value||0),all=t+d;document.getElementById('modalProductsTotal').textContent=`€${t.toFixed(2)}`;document.getElementById('deliveryTotal').textContent=`€${d.toFixed(2)}`;document.getElementById('modalTotal').textContent=`€${all.toFixed(2)}`}
function openCart(){document.getElementById('modal').classList.add('show');render()}function closeCart(){document.getElementById('modal').classList.remove('show')}function toggleMenu(){let n=document.querySelector('nav');n.style.display=n.style.display==='flex'?'none':'flex'}
function makeOrderNumber(){let d=new Date();return `ES-${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}-${Math.floor(1000+Math.random()*9000)}`}
function checkout(){if(!cart.length){alert('Количката е празна.');return}let name=document.getElementById('customerName').value.trim(),phone=document.getElementById('customerPhone').value.trim(),email=document.getElementById('customerEmail').value.trim(),address=document.getElementById('customerAddress').value.trim(),deliveryEl=document.getElementById('delivery'),paymentEl=document.getElementById('payment');if(!name||!phone||!email||!address){alert('Моля, попълни име, телефон, имейл и адрес.');return}if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){alert('Моля, въведи валиден имейл адрес.');return}if(!window.emailjs){alert('EmailJS не се зареди. Провери интернет връзката и опитай отново.');return}let orderNumber=makeOrderNumber(),productsText=cart.map(x=>`${x.name} × ${x.qty} — €${(x.price*x.qty).toFixed(2)}`).join('\n'),delivery=deliveryEl.selectedOptions[0].text,payment=paymentEl.selectedOptions[0].text,total=(cartProductsTotal()+parseFloat(deliveryEl.value||0)).toFixed(2),params={order_number:orderNumber,name,phone,email,address,delivery,payment,products:productsText,total};let button=document.querySelector('.checkout-box .btn.full');button.disabled=true;button.textContent='⏳ Изпращане...';emailjs.send(EMAILJS_SERVICE_ID,EMAILJS_TEMPLATE_ID,params).then(()=>{localStorage.removeItem('escooterCart');cart=[];render();closeCart();document.getElementById('successOrderNumber').textContent=orderNumber;document.getElementById('successModal').classList.add('show');['customerName','customerPhone','customerEmail','customerAddress'].forEach(id=>document.getElementById(id).value='');button.disabled=false;button.textContent='✅ Завърши поръчката'}).catch(e=>{console.error(e);alert('Не успяхме да изпратим поръчката. Провери EmailJS настройките и опитай отново.');button.disabled=false;button.textContent='✅ Завърши поръчката'})}
function closeSuccess(){document.getElementById('successModal').classList.remove('show')}
emailjs.init({publicKey:EMAILJS_PUBLIC_KEY});
renderProducts();render();
